spring:
  application:
    name: GymPlanningAi

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    flyway:
      enable: false
      baseline-on-migrate: true
      locations: classpath:db/migration

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true